inherit_gem:
  rubocop-rails:
    - config/default.yml

require: rubocop-rspec

AllCops:
  # Override rubocop-rails target version
  TargetRubyVersion: 2.4

  # Display Cop name, please!
  DisplayCopNames: true

  Exclude:
    # exclude rails commands
    - 'bin/**/*'

    # If set Exclude in "AllCops", it checks "node_modules" folder too
    - 'node_modules/**/*'

    - 'db/seeds.rb'
    - 'db/schema.rb'
    - 'db/migrate/*'
    - 'bin/setup'
    - 'bin/update'
    - 'vendor/**/*'
    - 'lib/templates/**/*'

RSpec/FilePath:
  Exclude:
    - 'spec/requests/*'
    - 'spec/routing/*'
    - 'spec/helpers/*'

RSpec/MultipleExpectations:
  Enabled: false

Style/DefWithParentheses:
  Enabled: true

Style/StringLiterals:
  Enabled: true
  EnforcedStyle: double_quotes

Style/ClassAndModuleChildren:
  EnforcedStyle: compact

Style/EmptyMethod:
  EnforcedStyle: expanded

Style/Documentation:
  Enabled: false

Metrics/LineLength:
  Exclude:
    - 'app/views/**/*.jbuilder'
