require:
  - rubocop-rails
  - rubocop-performance
  - rubocop-rspec
  - rubocop-factory_bot

AllCops:
  # Override rubocop-rails target version
  TargetRubyVersion: 3.3

  # Display Cop name, please!
  DisplayCopNames: true

  Exclude:
    # exclude rails commands
    - 'bin/**/*'

    # If set Exclude in "AllCops", it checks "node_modules" folder too
    - 'node_modules/**/*'

    - 'db/seeds.rb'
    - 'db/schema.rb'
    - 'db/migrate/*'
    - 'bin/setup'
    - 'bin/update'
    - 'config/application.rb'
    - 'vendor/**/*'
    - 'lib/templates/**/*'

RSpec/FilePath:
  Exclude:
    - 'spec/requests/*'
    - 'spec/routing/*'
    - 'spec/helpers/*'

RSpec/MultipleExpectations:
  Enabled: false

RSpec/NestedGroups:
  Max: 5

Style/DefWithParentheses:
  Enabled: true

Style/StringLiterals:
  Enabled: true
  EnforcedStyle: double_quotes

Style/ClassAndModuleChildren:
  EnforcedStyle: compact

Style/EmptyMethod:
  EnforcedStyle: expanded

Style/Documentation:
  Enabled: false

Metrics/LineLength:
  Exclude:
    - 'app/views/**/*.jbuilder'

Metrics/BlockLength:
  Exclude:
    - 'spec/**/*'
