language: ruby
rvm:
  - 2.4.1

bundler_args: --jobs=2

script:
  - bundle exec rake db:setup
  - bundle exec rake spec

cache:
  bundler: true
  yarn: true

services:
  - postgresql

addons:
  postgresql: "9.4"

before_install:
  - curl -o- -L https://yarnpkg.com/install.sh | bash
  - export PATH="$HOME/.yarn/bin:$PATH"
  - yarn install
