require "rails_helper"

# This spec was generated by rspec-rails when you ran the scaffold generator.
# It demonstrates how one might use RSpec to specify the controller code that
# was generated by Rails when you ran the scaffold generator.
#
# It assumes that the implementation code is generated by the rails scaffold
# generator.  If you are using any extension libraries to generate different
# controller code, this generated spec may or may not pass.
#
# It only uses APIs available in rails and/or rspec-rails.  There are a number
# of tools you can use to make these specs even more expressive, but we're
# sticking to rails and rspec-rails APIs to keep things simple and stable.
#
# Compared to earlier versions of this generator, there is very limited use of
# stubs and message expectations in this spec.  Stubs are only used when there
# is no simpler way to get a handle on the object needed for the example.
# Message expectations are only used when there is no simpler way to specify
# that an instance is receiving a specific message.
#
# Also compared to earlier versions of this generator, there are no longer any
# expectations of assigns and templates rendered. These features have been
# removed from Rails core in Rails 5, but can be added back in via the
# `rails-controller-testing` gem.

RSpec.describe Event::ParticipationsController, type: :controller do
  # This should return the minimal set of attributes required to create a valid
  # Event::Participation. As you add validations to Event::Participation, be sure to
  # adjust the attributes here as well.
  let(:valid_attributes) {
    FactoryBot.attributes_for(:event_participation)
  }

  let(:invalid_attributes) {
    FactoryBot.attributes_for(:event_participation, :invalid)
  }

  # This should return the minimal set of values that should be in the session
  # in order to pass any filters (e.g. authentication) defined in
  # Event::ParticipationsController. Be sure to keep this updated too.
  let(:valid_session) { {} }

  let(:event) {
    skip "not yet implemented"
    create(:event)
  }

  describe "GET #index" do
    it "returns a success response" do
      participation = Event::Participation.create! valid_attributes
      get :index, params: { event_id: event.to_param }, session: valid_session
      expect(response).to be_success
    end
  end

  describe "GET #show" do
    it "returns a success response" do
      participation = Event::Participation.create! valid_attributes
      get :show, params: { id: participation.to_param, event_id: event.to_param }, session: valid_session
      expect(response).to be_success
    end
  end

  describe "GET #new" do
    it "returns a success response" do
      get :new, params: { event_id: event.to_param }, session: valid_session
      expect(response).to be_success
    end

    it "should set the event from params" do
      get :new, params: { event_id: event.to_param }, session: valid_session
      expect(assigns(:event)).to eq event
      expect(assigns(:event_participation)).to be_a Event::Participation
      expect(assigns(:event_participation).event).to eq event
    end
  end

  describe "GET #edit" do
    it "returns a success response" do
      participation = Event::Participation.create! valid_attributes
      get :edit, params: { id: participation.to_param, event_id: event.to_param }, session: valid_session
      expect(response).to be_success
    end
  end

  describe "POST #create" do
    context "with valid params" do
      it "creates a new Event::Participation" do
        expect {
          post :create, params: { event_participation: valid_attributes, event_id: event.to_param }, session: valid_session
        }.to change(Event::Participation, :count).by(1)
      end

      it "redirects to the created event_participation" do
        post :create, params: { event_participation: valid_attributes, event_id: event.to_param }, session: valid_session
        expect(response).to redirect_to(Event::Participation.last)
      end
    end

    context "with invalid params" do
      it "returns a success response (i.e. to display the 'new' template)" do
        post :create, params: { event_participation: invalid_attributes, event_id: event.to_param }, session: valid_session
        expect(response).to be_success
      end
    end
  end

  describe "PUT #update" do
    context "with valid params" do
      let(:new_attributes) {
        skip("Add a hash of attributes valid for your model")
      }

      it "updates the requested event_participation" do
        participation = Event::Participation.create! valid_attributes
        put :update, params: { id: participation.to_param, event_participation: new_attributes, event_id: event.to_param }, session: valid_session
        participation.reload
        skip("Add assertions for updated state")
      end

      it "redirects to the event_participation" do
        participation = Event::Participation.create! valid_attributes
        put :update, params: { id: participation.to_param, event_participation: valid_attributes, event_id: event.to_param }, session: valid_session
        expect(response).to redirect_to(participation)
      end
    end

    context "with invalid params" do
      it "returns a success response (i.e. to display the 'edit' template)" do
        participation = Event::Participation.create! valid_attributes
        put :update, params: { id: participation.to_param, event_participation: invalid_attributes, event_id: event.to_param }, session: valid_session
        expect(response).to be_success
      end
    end
  end

  describe "DELETE #destroy" do
    it "destroys the requested event_participation" do
      participation = Event::Participation.create! valid_attributes
      expect {
        delete :destroy, params: { id: participation.to_param, event_id: event.to_param }, session: valid_session
      }.to change(Event::Participation, :count).by(-1)
    end

    it "redirects to the event_participations list" do
      participation = Event::Participation.create! valid_attributes
      delete :destroy, params: { id: participation.to_param, event_id: event.to_param }, session: valid_session
      expect(response).to redirect_to(event_participations_url)
    end
  end

end
